//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Postavshik = new HashSet<Postavshik>();
            this.Sotrudnik = new HashSet<Sotrudnik>();
        }
    
        public int Id { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public int House { get; set; }
        public string Corps { get; set; }
        public Nullable<int> Apartment { get; set; }
    
        public virtual ICollection<Postavshik> Postavshik { get; set; }
        public virtual ICollection<Sotrudnik> Sotrudnik { get; set; }
    }
}
