//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class chek
    {
        public int id_chek { get; set; }
        public Nullable<int> id_preparata { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> id_pokypki { get; set; }
    
        public virtual Pokypki Pokypki { get; set; }
        public virtual Preparat Preparat { get; set; }
    }
}
