//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Graphik
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Id_sotrudnik { get; set; }
    
        public virtual Sotrudnik Sotrudnik { get; set; }
    }
}
