//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int id_material { get; set; }
        public string name { get; set; }
        public string naznach { get; set; }
        public Nullable<int> id_kategorii { get; set; }
        public Nullable<int> id_hraneniya { get; set; }
        public Nullable<int> min_ostatok { get; set; }
        public Nullable<int> id_vracha { get; set; }
    
        public virtual Kategoriya_materiala Kategoriya_materiala { get; set; }
        public virtual Mesto_hraneniya Mesto_hraneniya { get; set; }
        public virtual Vrachi Vrachi { get; set; }
    }
}
