//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_Oborudovanie
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Id_sklad { get; set; }
        public Nullable<int> Number_stellazh { get; set; }
        public Nullable<int> Id_category { get; set; }
        public string Srok_hranenia { get; set; }
        public Nullable<int> Min_ostatok { get; set; }
        public Nullable<int> Ostatok { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Sklad Sklad { get; set; }
    }
}
