//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Pharmacy_MDKEntities : DbContext
    {
        public Pharmacy_MDKEntities()
            : base("name=Pharmacy_MDKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adres> Adres { get; set; }
        public virtual DbSet<chek> chek { get; set; }
        public virtual DbSet<Dogovor> Dogovor { get; set; }
        public virtual DbSet<Kategoriya_materiala> Kategoriya_materiala { get; set; }
        public virtual DbSet<Klient> Klient { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<Mesto_hraneniya> Mesto_hraneniya { get; set; }
        public virtual DbSet<Oborydovaniye> Oborydovaniye { get; set; }
        public virtual DbSet<Pokypki> Pokypki { get; set; }
        public virtual DbSet<Postavshiki> Postavshiki { get; set; }
        public virtual DbSet<Preparat> Preparat { get; set; }
        public virtual DbSet<Priem> Priem { get; set; }
        public virtual DbSet<Scheta> Scheta { get; set; }
        public virtual DbSet<Sotrydniki> Sotrydniki { get; set; }
        public virtual DbSet<Vrachi> Vrachi { get; set; }
        public virtual DbSet<zakaz> zakaz { get; set; }
        public virtual DbSet<zapros_zakaz> zapros_zakaz { get; set; }
    }
}
