//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokypki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pokypki()
        {
            this.chek = new HashSet<chek>();
        }
    
        public int id_pokypki { get; set; }
        public Nullable<int> id_klient { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> id_sotrydnika { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chek> chek { get; set; }
        public virtual Klient Klient { get; set; }
        public virtual Sotrydniki Sotrydniki { get; set; }
    }
}
