//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postavshik
    {
        public Postavshik()
        {
            this.Zakaz = new HashSet<Zakaz>();
        }
    
        public int Id { get; set; }
        public string Yuridich_name { get; set; }
        public string INN { get; set; }
        public Nullable<int> Kod_OKPO { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Id_address { get; set; }
        public Nullable<int> Id_dogovor { get; set; }
        public Nullable<int> Id_contacts { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Contacts Contacts { get; set; }
        public virtual Dogovor Dogovor { get; set; }
        public virtual ICollection<Zakaz> Zakaz { get; set; }
    }
}
