//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postavka
    {
        public Postavka()
        {
            this.Ostatok_preparat = new HashSet<Ostatok_preparat>();
        }
    
        public int Id { get; set; }
        public int Id_preparat { get; set; }
        public int Number_partiya { get; set; }
        public int Kolichestvo { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Skidka { get; set; }
        public int Number_zakaz { get; set; }
    
        public virtual ICollection<Ostatok_preparat> Ostatok_preparat { get; set; }
        public virtual Preparat Preparat { get; set; }
        public virtual Zakaz Zakaz { get; set; }
    }
}
