//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Priem
    {
        public int id_priema { get; set; }
        public Nullable<int> id_vracha { get; set; }
        public Nullable<int> id_klient { get; set; }
        public Nullable<int> id_dogovor { get; set; }
    
        public virtual Dogovor Dogovor { get; set; }
        public virtual Klient Klient { get; set; }
        public virtual Vrachi Vrachi { get; set; }
    }
}
