//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrydniki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sotrydniki()
        {
            this.Pokypki = new HashSet<Pokypki>();
        }
    
        public int id_sontrydnika { get; set; }
        public string familiya { get; set; }
        public string name { get; set; }
        public string otchestvo { get; set; }
        public Nullable<int> number { get; set; }
        public string email { get; set; }
        public string dolzhnost { get; set; }
        public Nullable<int> id_adres { get; set; }
        public Nullable<int> number_kv { get; set; }
    
        public virtual Adres Adres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pokypki> Pokypki { get; set; }
    }
}
