//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vrachi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vrachi()
        {
            this.Material = new HashSet<Material>();
            this.Oborydovaniye = new HashSet<Oborydovaniye>();
            this.Priem = new HashSet<Priem>();
        }
    
        public int id_vracha { get; set; }
        public string familiya { get; set; }
        public string name { get; set; }
        public string otchestvo { get; set; }
        public Nullable<int> number { get; set; }
        public string email { get; set; }
        public string dolzhnost { get; set; }
        public Nullable<int> id_adres { get; set; }
        public Nullable<int> number_kv { get; set; }
        public string job_grafik { get; set; }
        public Nullable<int> id_kabinet { get; set; }
    
        public virtual Adres Adres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material> Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oborydovaniye> Oborydovaniye { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Priem> Priem { get; set; }
    }
}
