//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public Zakaz()
        {
            this.Postavka = new HashSet<Postavka>();
        }
    
        public int Number { get; set; }
        public Nullable<System.DateTime> Date_zakaz { get; set; }
        public Nullable<System.DateTime> Date_otgruzka { get; set; }
        public Nullable<int> Id_postavshik { get; set; }
    
        public virtual ICollection<Postavka> Postavka { get; set; }
        public virtual Postavshik Postavshik { get; set; }
    }
}
