//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class zakaz
    {
        public string zakaz1 { get; set; }
        public Nullable<int> id_postavshik { get; set; }
        public Nullable<int> id { get; set; }
    
        public virtual Postavshiki Postavshiki { get; set; }
        public virtual zapros_zakaz zapros_zakaz { get; set; }
    }
}
