//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zapis_priem
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public Nullable<int> Id_klient { get; set; }
        public Nullable<int> Id_sotrudnik { get; set; }
        public Nullable<System.DateTime> Date_oformlenia { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual Sotrudnik Sotrudnik { get; set; }
    }
}
