//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ostatok_preparat
    {
        public int Id { get; set; }
        public int Id_postavka { get; set; }
        public int Ostatok { get; set; }
    
        public virtual Postavka Postavka { get; set; }
    }
}
